name: Run Multiple Make Commands

on:  # Adapt the trigger as needed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Define folders and make commands
      - name: Run Make Commands
        working-directory: .  
        run: |
          for folder in ex00 ex01 ex02; do
            cd $folder
            if [ -f Makefile ]; then 
              make fclean   # Example: Add a 'fclean' target
              make         # Build target
              make fclean
              make check   # Test target
              make fclean
              make memcheck
              # Add more 'make' commands if needed 
            fi
            cd .. 
          done
